### ISSUE TITLE
Is it possible to maintain the original resolution? 

### ISSUE THREAD

**Issue by Dustglaxy** [s1291/InkRasterPerspective#12]
Dear developer, 
Following the transformation, the resulting image appears quite blurry. How can this issue be addressed?

**Comment by s1291** [comment]
Could you please provide an example or more details about this issue?

**Comment by Dustglaxy** [comment]
Here is an example that I have followed your instructions.
Step1:
![s1](https://github.com/user-attachments/assets/3e5a83ab-1ce3-45a7-9c24-6a98d5f51564)

Step2:
![s2](https://github.com/user-attachments/assets/cafaa3a0-3335-4292-9b7e-6d2f57a7d44d)

Step3:
![s3](https://github.com/user-attachments/assets/3c11c3c4-b0cc-422e-a86e-d9efa2caf85e)

**Comment by s1291** [comment]
Thank you for the example. Could you please share the file so I can test that myself?

**Comment by Dustglaxy** [comment]
Dear developer,
I am so sorry for this late reply.  The example file is attached.
![drawing](https://github.com/user-attachments/assets/6d890231-ebdd-4839-8912-8a0854c95204)

**Comment by Dustglaxy** [comment]
Dear developer,
I am so sorry for this late reply. 
The example file is attached.
![drawing](https://github.com/user-attachments/assets/c824db77-1651-4b3d-a172-1b752aa73449)

**Comment by Dustglaxy** [comment]
Dear developer,
I am so sorry for this late reply.
The example file is attached.

![drawing](https://github.com/user-attachments/assets/ee473406-d63e-4341-9f08-eff8f1f6c655)

**Comment by Dustglaxy** [comment]
![Uploading drawing.svg…]()

**Comment by Dustglaxy** [comment]
Dear developer,
I am so sorry for this late reply.
And the example file is attached. 
Thanks for your time 
[drawing.zip](https://github.com/user-attachments/files/17069304/drawing.zip)

**Comment by s1291** [comment]
Scale the envelope (the rectangular path) to be larger than the original image, then apply the perspective transformation. Adjust the scale to suit your requirements for the final resolution.
 (See the SVG document below the following screenshot):
![image](https://github.com/user-attachments/assets/1ef023a0-bba3-42a9-af60-0f38dc0bcc55)

Example: 

[high_resolution_transformation.zip](https://github.com/user-attachments/files/17072917/high_resolution_transformation.zip)

**Comment by Dustglaxy** [comment]
Thanks very much
