### ISSUE TITLE
[Feature request]: Instead of ripping image, export selected objects before processing (or as an option)

### ISSUE THREAD

**Issue by MarioMey** [s1291/InkRasterPerspective#13]
I read the code and I saw that it rips the image (embedded or not) and then, it process that image. Instead of that, it could take the selected object, "export" it to have a new image and then, to process that image.

For example, I'm working with some objects that have multiples layers:

![imagen](https://github.com/user-attachments/assets/8372c861-3935-4c5b-ba7c-083c048dc749)

... that I would like to put with perspective in a poster. When using this extension, you know what it does: it applies a perspective to the original image. And every image of those objects is clipped or masked (and layers, and so...). In this case, RasterPerspective doesn't work.

Anyway, thanks for this fantastic extension ♥️.

**Comment by s1291** [comment]
Hi @MarioMey 

Sorry, I don't understand what you mean by '_...it **rips** the image..._'? 
I am not quite sure what you're asking exactly, but as a guess I would assume that you need to first convert your selection to a bitmap image (**Edit** → **Make a Bitmap Copy**) as shown below:

![image](https://github.com/user-attachments/assets/a4167af9-aefd-43cf-9dc5-df6e643299b6)
 


By default, the resolution is 96 dpi. You can increase that resolution (e.g., `300` dpi) from the Preferences dialog (**Edit** → **Preferences**), following the screenshot below:

![preferences_increase_resolution](https://github.com/user-attachments/assets/cf36af7c-10f5-405d-b2f8-228fda6f6e29)

Afterward, you can apply the perspective transformation on the new images.

Please let me know if that's what you are asking for.

**Comment by MarioMey** [comment]
Yes, that was I was looking for. I didn't know that "Make a Bitmap Copy". Well... wouldn't be great that InkRasterPerspective, instead of take the image from the object, it apply a "Make a Bitmap Copy" and then process it? It could also have some options: to do it in the old way or the Bitmap Copy and a resolution option.

Look at this. The upper image is a masked one and I applied the extension. The one from the bottom, I first click on "Make a Bitmap Copy" and then apply the extension.

![imagen](https://github.com/user-attachments/assets/4f3bec9c-1500-4c5e-84cf-135a49ceefb3)
