### ISSUE TITLE
Not working on windows - issues with deconstructing self.svg.selection and uuto unit

### ISSUE THREAD

**Issue by cia05rf** [s1291/InkRasterPerspective#2]
Using this package on windows had to fix this error.

issue:
----
will not deconstruct `the_image_node, envelope_node = self.svg.selection`
error of `missing expected atribute units` when calling `unit_to_vp`

Created fix and will submit.

Thanks for the excellent package.

**Comment by cia05rf** [comment]
I have a fix on my local repo so make me a contributor and I'll make a branch/PR

**Comment by s1291** [comment]
Hello,

Thank you for reporting that. Could you please specify what version of Inkscape you are using and what is the error message you are getting?

**Comment by cia05rf** [comment]
Inkscrape V1.0.1.
Error message: Your selection must contain an image and a path with at least 4 points.

**Comment by cia05rf** [comment]
I have a fix for it which works fine on my windows machine

**Comment by s1291** [comment]
I haven't tested this extension with old versions but I expect it to break due to API change between versions.
You're welcome to submit a PR.
