### ISSUE TITLE
Inkscape 1.0.2-2: Your selection must contain an image and a path with at least 4 points.

### ISSUE THREAD

**Issue by WelliSolutions** [s1291/InkRasterPerspective#3]
I tried the extension with Inkscape 1.0.2-2 on Windows 10 and I got the error message:

> Your selection must contain an image and a path with at least 4 points.

I'm 100% sure I do the steps correctly. Here's how my selection looks like when I invoke the command.

![image](https://user-images.githubusercontent.com/14279507/201731189-bcdcbd61-64a0-4917-883e-eab551951c44.png)

I don't know how to debug the extension in Inkscape, but I have debugging skills in general. Maybe I just need a pointer on how to enable extension debugging.

**Comment by s1291** [comment]
Could you please share your SVG file?
Also, I highly recommend to upgrade to the latest version of inkscape (currently: inkscape 1.2.1).

**Comment by WelliSolutions** [comment]
I think this is a duplicate of #4. I didn't get the embed/link dialog because I had set to link by default.
