### ISSUE TITLE
Inkscape 1.2.1: PIL.UnidentifiedImageError: cannot identify image file if image is linked instead of embedded.

### ISSUE THREAD

**Issue by WelliSolutions** [s1291/InkRasterPerspective#4]
Since I used a quite old version in issue #3, I thought I'd better upgrade to the latest version of Inkscape. Now I get this error:

> Traceback (most recent call last):
  File "C:\Program Files\Inkscape\share\inkscape\extensions\imagePerspective.py", line 179, in <module>
    imagePerspective.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 231, in run
    self.save_raw(self.effect())
  File "C:\Program Files\Inkscape\share\inkscape\extensions\imagePerspective.py", line 123, in effect
    orig_image = PIL_Image.open(io.BytesIO(img_data))
  File "C:\Program Files\Inkscape\lib\python3.10\site-packages\PIL\Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001ca3022c900>

My image is a 1314x2592 pixel 24 bit PNG file with a size of 6.99 MB, if that matters.
Same error for a 3072x2048 pixel 8 bit BMP file with a size of 6 MB.

The problem disappears if the file is embedded instead of linked.
![image](https://user-images.githubusercontent.com/14279507/201734800-02cfc065-eb45-4ea6-8b3e-cf1d6dd6324b.png)

**Comment by s1291** [comment]
Thank you for your feedback!
I will push a fix soon.

**Comment by s1291** [comment]
**Update:**

@WelliSolutions : I have pushed an update. I have tested the patch on ~Linux only~ both Linux and Windows and it seems to work flawlessly.

Please feel free to re-open the issue if you still encounter issues with linked images.

**Comment by WelliSolutions** [comment]
I get an error message: 

> Invalid path: C:\H:\M\t....bmp

Note that it reports 2 drive letters here: C:\ and H:\

In the XML editor, I see the file:/// protocol

![image](https://user-images.githubusercontent.com/14279507/201996790-43287465-c62f-4d7a-b22e-97a88bc94949.png)

whereas I can see in the comment
```python
# on Windows, paths are relative (by default?) and they do not start with file:///
```
that the script doesn't expect file:///

**Comment by s1291** [comment]
That issue occurs only on windows, and it requires special treatment. I have added a patch.

**Comment by WelliSolutions** [comment]
The following works for me:
```python
import os
import urllib.parse as urlparse
import urllib.request
[...]
    def extract_image(self, node):
        """Extract the node as if it were an image."""
        xlink = node.get("xlink:href")
        if not xlink.startswith("data:"):
            # on Windows, paths are relative (by default?) and they do not start with file:///
            _path = urlparse.urlparse(xlink).path
            parsed = urlparse.urlparse(xlink)
            host = "{0}{0}{mnt}{0}".format(os.path.sep, mnt=parsed.netloc)
            _path = os.path.normpath(os.path.join(host, urllib.request.url2pathname(urlparse.unquote(parsed.path))))
            path = self.absolute_href(_path or "", cwd=os.path.dirname(self.options.input_file))
            starts_with_file = xlink.startswith("file:")
            if starts_with_file or os.path.isfile(path):
               

                if os.path.isfile(path):
                    # open the file and encode it
                    # I know, this is a horrible workaround (to b64 encode the image), but 
                    # for the sake of it, that provides an easy workaround for linked images,
                    # and let's ignore it for now. (#FIXME)
                    with open(path, "rb") as linked_img_file:
                        data = base64.b64encode(linked_img_file.read())
                        #return decodebytes(data.encode("utf-8"))
                        return decodebytes(data)
                    
                else:
                    inkex.errormsg(f"Invalid path: {path}")


            return # Not embedded image data

        try:
            data = xlink[5:]
            (mimetype, data) = data.split(";", maxsplit=1)
            (base, data) = data.split(",", maxsplit=1)
        except ValueError:
            inkex.errormsg("Invalid image format found")
            return

        if base != "base64":
            inkex.errormsg("Can't decode encoding: {}".format(base))
            return

        file_ext = self.mime_to_ext(mimetype)
        return decodebytes(data.encode("utf-8"))
```

But I don't know if I broke it for Linux this way :-D

**Comment by WelliSolutions** [comment]
The linked answer of https://stackoverflow.com/a/43925228/5920411 using `url2pathname` does not work. The answer misses the third / in `file:///` and uses a Linux path in that example. Having 2 colons `:`, one for `file:` and one for `C:` breaks `url2pathname`. 

I was following https://stackoverflow.com/a/61922504/480982

**Comment by s1291** [comment]
Please use the latest commit: https://github.com/s1291/InkRasterPerspective/commit/897d8eb4532eac2032d4dc17f8c30fe4c3b053fe

**Comment by s1291** [comment]
I have tested the latest commit: https://github.com/s1291/InkRasterPerspective/commit/897d8eb4532eac2032d4dc17f8c30fe4c3b053fe on both Linux and Windows (for linked images where the partition letter is not necessarily `C:`) and it seems to work. The reason whythe error message shows both `C:` and `H:` letter in the path is caused by `os.path.abspath`.

**Comment by WelliSolutions** [comment]
Okay, yes, that version seems to work. Thanks for the collaboration.

**Comment by s1291** [comment]
> Okay, yes, that version seems to work. Thanks for the collaboration.

Many thanks for providing these edge cases.
