### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'Transform'

### ISSUE THREAD

**Issue by cheshirekow** [s1291/InkRasterPerspective#7]
This is on Ubuntu 22.04
Inkscape verison: Inkscape 1.1.2 (0a00cf5339, 2022-02-04)
Python version in my environment: 3.10.6
PIL provided by (in my environment): Pillow==9.1.0

I don't know if inkscape or this extension embed their own python or use the environment python but the above python and Pillow are what I have installed in the environment where I run Inkscape. I assume that is what is being used. 

~~~
Traceback (most recent call last):
  File "/home/josh/.config/inkscape/extensions/InkRasterPerspective/imagePerspective.py", line 195, in <module>
    imagePerspective.run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "/home/josh/.config/inkscape/extensions/InkRasterPerspective/imagePerspective.py", line 174, in effect
    PIL_Image.Transform.PERSPECTIVE,
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Transform'
~~~

**Comment by dja001** [comment]
I had the same problem with PIL version 7.0.0

In this version of PIL, the methods/attributes PERSPECTIVE and BICUBIC are not in
```
PIL.Image.Transform.PERSPECTIVE
PIL.Image.Transform.BICUBIC
```
but rather one level up in
```
PIL.Image.PERSPECTIVE
PIL.Image.BICUBIC
```

I could get the extension to work (thanks @s1291!) by changing lines 172-177 of `$HOME/.config/inkscape/extensions/InkRasterPerspective/imagePerspective.py`
from:
```
         image = transp_img.transform(
             (final_w, final_h),
             PIL_Image.Transform.PERSPECTIVE,
             coeffs,
             PIL_Image.Transform.BICUBIC,
         )
```
to
```
         image = transp_img.transform(
             (final_w, final_h),
             PIL_Image.PERSPECTIVE,
             coeffs,
             PIL_Image.BICUBIC,
         )
```
hope this helps.
